{% set version = "2.0" %}

package:
  name: fmipp
  version: {{ version }}

source:
  url: https://github.com/fmipp/fmipp/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 16bd8fbed77fbcab2988eda89f4760c08b3857dd45f78879290c8b0725fcca1b

build:
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake
    - ninja
  host:
    - swig
    - libboost-devel
    - sundials
    - python
  run:
    - python

test:
  imports:
    - fmippim

about:
  home: https://fmipp.readthedocs.io/en/latest
  license: BSD-2-Clause
  license_file: FMIPP_LICENSE
  summary: A High-level Utility Package for FMI-based Software Development
  dev_url: https://github.com/fmipp/fmipp

extra:
  recipe-maintainers:
    - jschueller
