{% set version = "1.2" %}

package:
  name: fmipp
  version: {{ version }}

source:
  # no tarball available, no git tag
  git_url: git://git.code.sf.net/p/fmipp/code
  git_rev: 565836e255a73d013b3b74331d56f24ebf8b5408

build:
  number: 3
  features:
    - vc9  # [win and py27]
    - vc14  # [win and py>=35]
  # module fails to import on x86
  skip: true  # [win32]

requirements:
  build:
    - toolchain
    - cmake
    - swig
    - boost 1.65.1
    - sundials 2.7.*
    - python
  run:
    - boost 1.65.1
    - sundials 2.7.*
    - python

test:
  imports:
    - fmippim

about:
  home: http://fmipp.sourceforge.net
  license: BSD 2-Clause
  license_file: FMIPP_LICENSE
  summary: A High-level Utility Package for FMI-based Software Development

extra:
  recipe-maintainers:
    - jschueller
