travis:
  secure:
    BINSTAR_TOKEN: JUtA3BvRo5YcwAOiNLiT4iTY+sz5inWfkTuW/aeBhSOf/Hegdak9UooWG/O31/dPMnO6Zhoj/8Pi5vi4U8s6UyVhtAu4KpdKhTJJ2jSGg7E0aXpB7PzI30NWMe43QkPi5QZ08S7baN9IDW8SHcIu+dEQkRbefAvaROnVFdcRe0n7GXTXH+SMNEl1xj4xNOkAV5JfmY50ACdggHxFCjHUJJ2opUhM8ZtPYop/c1ZH39nad35aT0f6cfMeP7r7EY2qvTCDfEPBNRPDxDj6HlmMUyrPDBplNIv6sxCOTbuasvJgwDYL44FAxlxpcka7va6fec8bbjT0KpyXcK2Eaan63tfTR4BDKxuTX/g+HiLyjw5NwYdE9PJNbEOB/wAEq7wir1bqF0yjVE16yZe/Rieu5iSSDEayoPlzdXFpE3e19OyGqVpvBhM9vRNbri31392NB7j9ZR+VSXFlXL09zHdoO3u70SuWliojgfcZ08wGeiaWWY8X3MciCwrxUYhcRMaZOyYB/08+IhfijxEWZQnrtdpX2wbUegJDn16ge01jMj8vjmTjxeGSyJw4T06tpnW+EjThl9UAPIctZfhP0p53SdlHoiyjA0czAjCKMcqLV25EKE52IdSTVVMMbOYhdmuKgEfKIZ8g0bmOJaTobLpiOPVVpz87iMRmNfTN1mxq/3o=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
