travis:
  secure:
    BINSTAR_TOKEN: e23euIG9B9iI1Pu1xoylDSqnh7HDAP66Af8J3ZauMHoHpuQ6Nesoxw/yfxuoyyGARSjvKl7XbrbbNXHVWs7pUPsslvC6y/Tu8dorwt8N2rf6Au92kDhPbbEmXlMTuKZqtquviJsuZHjCWpoF+vrI30T26fVqWTOYLLdUEI/yPvHXykM57R1H6su0QkMVjT2MHtco+ZRQCGQiIRAn7HF37w03LXcRfcUUVPNXup738PQbF/ZUV/dQWeWWmU3SpvftUmF8UGrKHOlaS0L1xzt7e4CarALQtVW+bLFWZzvgRpU9ZCaL7mJgUc9fTQG2doL92+pD7ROsD4iU7I/YaYw51+p4d574WPt3N/pZGbV0eJ6J/ij31AMw7IqCfdWwirhH3MnF5jYLwkOyPtz3jtx91lbPZPR7eDzKom+aZJJvHhUBCjHl+40667JghVj6Xru4ar9hdv7Wcw5d9zsoTVWLs9/T2ATUJ9brpFgXtWsDGAqKpMAmL1NYtkPvkDzczs9WbVu0aS1tJRK8nKTIa3NcPtcpSj1rJLz8uLGhK7eyP8g1R4oFiglurCrbz+qSe8cBSBZtKnp5K0mhotHi4JAmwRESMJu30AAQ5bi6DKtldyWVzac593KaePHICsa9jvJuf1+ZMAlG5obceyUsWxY7rpobWYslKbsAeKT0JqdVkIU=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
