travis:
  secure:
    BINSTAR_TOKEN: Ly3i7MSTisj1C5cwGUetxBOlCknBoVulRLlNPUYltxesNJVzqV5V9kriACOJRcc/il6I8xJchNATnGWtXUTgd/Tksa4VZ6CDB1BeG4FjxLa+MJ/FGGKIKItSOqBjd5k6kwXwUS71DR6xOMf46gUbqCoCkpDshSstAfc0ZP4UB6iPuxdIAbSqdkBmFHx8fWFnXNMzO2AOdVw4W+DvR0JTIKhI9l7qI9aSdMYrHJvWNCXnq9InFsTAFHTCFcpB9C3sWl8w5c8PnYuyhkLeFETVGp7TwpVNEdlzebiNtUvyDs7EZDi1MbGIyjJy+W/b7wQEIQjT3CJHQ2ZQonQt8rG6LZ5dvcziUJ+Z+NC4go2FJqcsIsYkXcBVdFet67tqJBLR+OnsuGwAacmrE20VLh4+ctvf9i72UzyfQNffIGmTNjgO8c216HFqHlllA7GxnsDO5Cwz2YeH3ATObwGoIjuKzITrK42YAE6NL/7dWEB46BRhliUgNSHj9+ajIfcA/lcgBd8TAkbDZCkCGMjtHrGvJbLRAg1DbSt6uyXuK/BfF85HkDavu6TyU7CpOgt6vyQp5VizrZtWG1/prCNO6RK6PC5MTaM19n2KFn9/c549aJFgMQh83yP550RrJ/CEiL43rOousCsUi2c9uTKM0KIiU+Sii4iluH//rotr+gK8khk=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
